export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_LIST_SWITCH = 'ARTICLE_LIST_SWITCH'
export const SCROLLDATA = 'SCROLLDATA'

// demo
export const DEMO__VUEX_FOLLOW = 'DEMO__VUEX_FOLLOW'
export const DEMO__VUEX_FOLLOW_PENDING = 'DEMO__VUEX_FOLLOW_PENDING'
